# Generated by Django 3.2.6 on 2021-08-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='current_institute',
            field=models.CharField(default=None, max_length=150, verbose_name='Current Institute'),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(default=None, max_length=20, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='account',
            name='preferred_higher_education',
            field=models.CharField(default=None, max_length=150, verbose_name='Preferred Higher Education'),
        ),
    ]
