# Generated by Django 3.2.6 on 2021-08-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210811_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='current_institute',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Current Institute'),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='account',
            name='preferred_higher_education',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Preferred Higher Education'),
        ),
    ]
